"""Phase-16 frequency-upgrade test.

Re-runs the production strategy on **synthetic 4h bars** generated by
`DataFetcher._synth_4h_from_daily` for BTC-USD and ETH-USD only. The
mirrors are daily-only, so each daily OHLCV bar is split into 6 4h
sub-bars at 00/04/08/12/16/20 UTC: the day's OHLC envelope is preserved,
volume is uniformly spread across the six sub-bars (`volumespread`),
and prices interpolate from `day_open → day_close` linearly.

Holds every Phase-14 production knob fixed except:
  * `universe`     → [BTC-USD, ETH-USD] (the only symbols with real
                     intraday-equivalent data via the synthetic split)
  * `timeframe`    → "4h"
  * `max_holding_bars` → 60 (= 10 daily × 6 4h-per-day, semantic
                          equivalent of the Phase-14 hold window)
  * `max_position_pct` → swept across {0.05, 0.10, 0.20}
  * `initial_capital` → $1,000 (matches Phase-15 sizing-sweep baseline)

Reports trade count, PF, trade-weighted-rf=0 Sharpe, return, max DD,
DD duration, and final equity per sizing.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from quant_trader.backtest import Backtester, compute_metrics
from quant_trader.data import DataFetcher, DataPipeline


SIZES = [0.05, 0.10, 0.20]
INITIAL_CAPITAL = 1_000.0
UNIVERSE = ["BTC-USD", "ETH-USD"]
TIMEFRAME = "4h"
# 10 daily bars × 6 sub-bars/day so the holding-window semantic matches
# Phase-14's daily setting.
MAX_HOLDING_BARS_4H = 60


def _bt(settings: dict, max_pct: float) -> Backtester:
    return Backtester(
        initial_capital=INITIAL_CAPITAL,
        commission_rate=settings.get("commission_rate", 0.001),
        slippage_rate=settings.get("slippage_rate", 0.0005),
        max_position_pct=max_pct,
        max_drawdown_kill=settings.get("max_drawdown_kill", 0.10),
        max_concurrent_positions=settings.get("max_concurrent_positions", 5),
        confidence_threshold=settings.get("signal_confidence_threshold", 0.45),
        stop_atr_mult=settings.get("stop_atr_mult", 1.5),
        take_profit_atr_mult=settings.get("take_profit_atr_mult", 2.5),
        max_holding_bars=MAX_HOLDING_BARS_4H,
        seed=settings.get("seed", 42),
        regime_filter=settings.get("regime_filter", True),
        regime_slope_threshold=settings.get("regime_slope_threshold", 0.0),
        long_only=settings.get("long_only", True),
        atr_pct_low=settings.get("atr_pct_low", 0.0),
        atr_pct_high=settings.get("atr_pct_high", 1.0),
        min_agreement_delta=settings.get("min_agreement_delta", 0.05),
    )


def main() -> int:
    settings = yaml.safe_load(open("quant_trader/config/settings.yaml"))
    fetcher = DataFetcher()
    pipe = DataPipeline(fetcher)
    data = pipe.fetch_all(
        universe=UNIVERSE,
        timeframe=TIMEFRAME,
        start=settings["backtest_start"],
        end=datetime.now(timezone.utc),
    )
    bars = {s: len(d) for s, d in data.items()}
    print(f"4h bars per symbol: {bars}")

    rows: list[dict] = []
    for size in SIZES:
        bt = _bt(settings, size)
        bt_summary = bt.run(data)
        m = compute_metrics(bt_summary, risk_free_rate=0.0, timeframe=TIMEFRAME)
        rows.append({
            "max_position_pct": size,
            "initial_capital": INITIAL_CAPITAL,
            "n_trades": m["n_trades"],
            "win_rate": m["win_rate"],
            "profit_factor": m["profit_factor"],
            "total_return": m["total_return"],
            "max_drawdown": m["max_drawdown"],
            "max_drawdown_duration_days": m["max_drawdown_duration_days"],
            "final_equity": m["final_equity"],
            "sharpe_tw_rf0": m["sharpe_trade_weighted"],
            "invested_periods": m["invested_periods"],
            "total_periods": m["total_periods"],
        })

    header = (
        f"{'max_pos_%':>10} | {'trades':>6} | {'PF':>5} | {'Sharpe':>6} | "
        f"{'total_ret':>9} | {'max_dd':>7} | {'dd_days':>7} | {'final_eq':>10}"
    )
    sep = "-" * len(header)
    print(
        f"\nPhase-16 frequency-upgrade test (synthetic 4h bars on "
        f"{UNIVERSE}, $1,000 starting balance)"
    )
    print(sep)
    print(header)
    print(sep)
    for r in rows:
        print(
            f"{r['max_position_pct']:>9.2%} | "
            f"{r['n_trades']:>6d} | "
            f"{r['profit_factor']:>5.2f} | "
            f"{r['sharpe_tw_rf0']:>+6.2f} | "
            f"{r['total_return']:>+9.2%} | "
            f"{r['max_drawdown']:>+7.2%} | "
            f"{r['max_drawdown_duration_days']:>7.0f} | "
            f"${r['final_equity']:>9,.2f}"
        )
    print(sep)

    out = Path("backtest/results/sizing_sweep_4h.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps(
            {
                "config": {
                    "universe": UNIVERSE,
                    "timeframe": TIMEFRAME,
                    "initial_capital": INITIAL_CAPITAL,
                    "max_holding_bars": MAX_HOLDING_BARS_4H,
                    "synth_method": "volumespread (daily → 6× 4h, OHLC envelope preserved, vol/6 per sub-bar)",
                    "signal_confidence_threshold": settings["signal_confidence_threshold"],
                    "regime_filter": settings.get("regime_filter"),
                    "long_only": settings.get("long_only"),
                    "max_drawdown_kill": settings.get("max_drawdown_kill"),
                },
                "results": rows,
            },
            indent=2,
        )
    )
    print(f"\nSaved {out}")

    # Acceptance criterion: any sizing with PF > 1.3 AND n_trades > 400.
    qualifies = any(r["profit_factor"] > 1.3 and r["n_trades"] > 400 for r in rows)
    print(f"\nQualifies for commit (any sizing PF>1.3 & n>400): {qualifies}")
    return 0 if qualifies else 1


if __name__ == "__main__":
    sys.exit(main())
